services:
  shop:
    hostname: shop
    build:
      context: .
    environment:
      - CEIS_SHOP_HOSTNAME=shop
      - CEIS_MONITOR_HOSTNAME=ceis
    ports:
      - "8050:8050"
    # Masks sourcecode in container so changes are synced to host
    volumes:
      - ./:/app/
    entrypoint: ["poetry", "run", "shop"]

  ceis:
    hostname: ceis
    environment:
      - CEIS_MONITOR_HOSTNAME=ceis
      - CEIS_SHOP_HOSTNAME=shop
    build:
      context: .
    ports:
      - "8051:8051"
    volumes:
      - ./:/app/
    entrypoint: ["poetry", "run", "ceis"]

  graphdb:
    hostname: graphdb
    build:
      context: clab_ceis/assets/graphdb
    ports: 
    - 7200:7200
    - 7300:7300
    volumes:
      - ceis-graphdb-volume:/opt/graphdb/home

volumes:
  ceis-graphdb-volume:
