services:
  shop:
    build:
      context: .
    ports:
      - "8050:8050"
    # Masks sourcode in container so changes are synced to host
    volumes:
      - ./:/app/
    network_mode: host
    entrypoint: ["poetry", "run", "./clab_ceis/shop.py"]

  ceis:
    build:
      context: .
    ports:
      - "8051:8051"
    volumes:
      - ./:/app/
    network_mode: host
    entrypoint: ["poetry", "run", "./clab_ceis/ceis.py"]

  graphdb:
    hostname: graphdb
    build:
      context: clab_ceis/assets/graphdb
    ports: 
    - 7200:7200
    - 7300:7300
    # Masks sourcode in container so changes are synced to host
    volumes:
      - ceis-graphdb-volume:/opt/graphdb/home
    network_mode: host

volumes:
  ceis-graphdb-volume:
